"""Add search vector

Revision ID: 3896268e9857
Revises: 6b5d4a5f94ef
Create Date: 2021-08-06 18:50:30.155464

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy_searchable import sync_trigger

# revision identifiers, used by Alembic.
revision = '3896268e9857'
down_revision = '6b5d4a5f94ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    op.add_column('product', sa.Column('search_vector', sqlalchemy_utils.types.ts_vector.TSVectorType(), nullable=True))
    sync_trigger(conn, 'product', 'search_vector', ['name', 'brand', 'style'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'search_vector')
    # ### end Alembic commands ###
