"""Update price column to Numeric type

Revision ID: 3fe587548855
Revises: 6221df87bb92
Create Date: 2021-10-05 13:08:35.307262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3fe587548855'
down_revision = '6221df87bb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'price', 'price',
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'price', 'price',
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=postgresql.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
