POPULAR_STYLES = [
    'Aged Sour Ale',
    'Weissbier',
    'Hoppy Saison',
    'DDH DIPA',
    'Fruited Sour',
    'Single Hop IPA',
    'Double Dry-hopped IPA',
    'Hazy DIPA',
    'Double Dry-hopped Double IPA',
    'Pilsner Beer',
    'Pineapple Sour IPA',
    'Oat Cream IPA',
    'Robust Porter',
    'Imperial Cream Sour',
    'Easy IPA',
    'Dry Hopped Kettle Sour',
    'Dark',
    'English Ale',
    'Dry Gin',
    'Session Hazy IPA',
    'Blackcurrant Lambic',
    'Salted Lime Gose',
    'Strong Pale Lager',
    'West Coast DIPA',
    'Fruit Gose',
    'Belgian Triple',
    'Whiskey',
    'Peach Lambic',
    'Red IPA',
    'Non-Alcoholic',
    'Belgian Double IPA',
    'Smoked',
    'Dry-hopped Sour Ale',
    'IIPA',
    'Barrel Aged Stout',
    'Seltzer',
    'Sour Fruited',
    'Belgian White Ale',
    'Alcoholic Seltzer',
    'Citrus Session IPA',
    'Single Estate Tequila',
    'Imperial Chocolate Stout',
    'DDH Hazy IPA',
    'Maibock',
    'Belgian Quadrupel',
    'Unfiltered Double IPA',
    'Witbier',
    'Oatmeal Stout',
    'Extra Pale Ale',
    'Pastry Stout',
    'Black IPA',
    'Milk Stout',
    'Barrel Aged Imperial Stout',
    'Ice Cream Sour',
    'Cocktail',
    'Red Rice Ale',
    'Wild Ale',
    'Wit Beer',
    'Golden Tripel',
    'Sour IPA',
    'Trappist',
    'DDH IPA',
    'Fruit Ale',
    'Imperial Pastry Stout',
    'Barley Wine',
    'Cream Ale',
    'Ginger Beer',
    'Flanders Red Ale',
    'Summer Ale',
    'Triple IPA',
    'Russian Imperial Stout',
    'Hazy Pale Ale',
    'Indian Pale Ale',
    'Tropical Pale Ale',
    'Hazy Double IPA',
    'White Ale',
    'DIPA',
    'Fruited Sour Ale',
    'Strong Ale',
    'Session Pale Ale',
    'Brown Ale',
    'Saison',
    'American IPA',
    'American Pale Ale',
    'Sour',
    'Lambic',
    'Pale Lager',
    'Dubbel',
    'West Coast IPA',
    'Session Ale',
    'Imperial Stout',
    'Dark Ale',
    'India Pale Ale',
    'NEIPA',
    'Double IPA',
    'Hazy IPA',
    'Quadrupel',
    'Amber Ale',
    'Wheat',
    'New England IPA',
    'Tripel',
    'Mead',
    'Porter',
    'Fruit Beer',
    'Ale',
    'Wheat Beer',
    'Pilsner',
    'Imperial IPA',
    'Wheat Ale',
    'Cider',
    'Hazy Ale',
    'Gose',
    'Session IPA',
    'Golden Ale',
    'Sour Ale',
    'Belgian Ale',
    'Stout',
    'Lager',
    'Pale Ale',
    'IPA',
]


POPULAR_BRANDS = [
    'Grolsch',
    'San Miguel',
    'Hahn',
    'Victoria Bitter',
    'Adam & Eve',
    'Tooheys',
    'Kingfisher',
    'Coopers',
    'LAOSHAN',
    'Beerfest',
    'Hawkes',
    'Stone And Wood',
    'Redpoint Brewing',
    'Thirsty Beer Shop',
    'Redpoint Brewing',
    'Radeberger',
    'Darling Brew',
    'Budweiser',
    'Hacker-Pschorr',
    'Woodstock',
    'Boatrocker',
    'Hop Nation Brewing',
    'Steinlager',
    'Fruli',
    'Mornington Peninsula',
    'Fraser\'s Folly',
    'To Ol',
    'Offshoot Beer',
    'Dab Dortmunder',
    'GREVENSTEINER',
    'Benediktiner',
    'Dainton',
    'The Hills Cider',
    'Kronenbourg',
    'Jever',
    'Moondog',
    'High West Distillery',
    'Urbanaut',
    'Brouwerij Boon',
    'Franzikaner',
    'Westmalle Trappist',
    'Root Sellers Inc',
    'Firestone Walker',
    'Chimay',
    'Bodriggy',
    'Pilsner Urquell',
    'Trappistes Rochefort',
    'Älska',
    'Lotte Chilsung',
    'James Squire',
    'Wilde',
    'Cigar City',
    'bira91',
    'Burley Oak',
    'Modern Times',
    'Boon',
    'Yoho',
    'Tsingtao',
    'Stockade Brew',
    'Tequila Corazón de Agave',
    'Amager Bryghus',
    'Mort Subite',
    'Sweetwater',
    'North Coast',
    'Spoetzl',
    'Blue Moon',
    'Wychwood',
    'Brasserie Dupont',
    'Redpoint',
    'Fremont',
    'Beerfarm',
    'Sailor\'s Grave Brewing',
    'Little Creatures',
    'Specific Gravity Beverage Company',
    'Pasteur Street',
    'Duncan\'s',
    'Fourpure',
    'Schfferhofer',
    'Buffalo Trace Distillery',
    'Kasteel',
    'Parrotdog',
    'Zeffer',
    'American Taproom x Spiffy Dapper',
    'Drakes',
    'Pasteur Street Brewing',
    'Kapuziner',
    'Soul Barrel',
    'Bodriggy Brewing',
    'Thatchers',
    'Off Day',
    'Fourpure Brewing',
    'Chillhops Brewing',
    'Verhaeghe',
    'KAISERDOM',
    'Hobo Brewing',
    'Dupont Tourpes',
    'SweetWater Brewing',
    'Hitachino Nest Beer',
    'Moon Dog',
    'Stone & Wood',
    'Omnipollo',
    'Rye & Pint',
    'Anderson Valley',
    'North Coast Brewing',
    'Hitachino Nest',
    'North Coast Brewing',
    'Rogue Ales',
    'Gweilo',
    'To Øl',
    'Veltins',
    'Liberty Brewing',
    'Boon Oude Geuze',
    'Moon Dog',
    'Orval',
    'Pabst',
    'Brooklyn',
    'Brouwerij Verhaeghe',
    'Young Master',
    'Fourpure Brewing',
    'Stockade Brew',
    'Dupont',
    'Estrella',
    'Samuel Adams',
    'Gosnells Mead',
    'Coedo',
    'Gosnells of London',
    'No Brand',
    'Dogfish Head',
    'Brouwerij 3 Fonteinen',
    'Otherside Brewing',
    'LA TRAPPE',
    'Hoegaarden',
    'Epic',
    'TAIWAN BEER',
    'Two Tribes',
    'Rochefort',
    'Affligem',
    'Barossa Valley Brewing',
    'Brouwerij St. Bernardus',
    'Devil\'s Peak',
    'Paulaner',
    'Archipelago',
    'Co-conspirators Brewing',
    'Sierra Nevada Brewing',
    'Deep Creek',
    'Delirium',
    'Levante',
    'Gosnells',
    'Adroit Theory Brewing',
    'Gorilla',
    'Thatchers Cider',
    'Pabst Blue Ribbon',
    'La Trappe',
    '3 Fonteinen',
    'Leffe',
    'ParrotDog',
    'Founders Brewing',
    'Erdinger',
    'Van Honsebrouck',
    'Van Steenberge',
    'Ska',
    'Otherside Brewing',
    'Gage Roads',
    'The 1925',
    'Maui',
    'Salt Beer Factory',
    'Founders Brewing',
    'Pirate Life Brewing',
    'Atomic',
    'Westmalle',
    'Feral Brewing',
    'The 1925 Brewing',
    'St Bernardus',
    'Heretic Brewing',
    'Magic Rock Brewing',
    'Brewerkz',
    'Rochefort',
    'Huyghe',
    'Behemoth Brewing',
    'Bosteels',
    'Deep Creek',
    'Wychwood',
    'Young Master',
    'Pizza Port',
    'Mother Earth',
    'Vocation',
    'Founders Brewing',
    'Heretic',
    'Anderson Valley Brewing',
    'Thornbridge',
    'Brewlander &',
    'Mike Hess',
    'Stockade',
    'Stone Brewing',
    'Vedett',
    'Off Day Beer Company',
    'Otherside',
    'Lion City Meadery',
    'Lion Brewery',
    'St. Bernardus',
    'Wayward',
    'Anderson Valley Brewing',
    'Brothers',
    'Duvel',
    'Playground',
    'BrewDog',
    'Blasta Brewing',
    'Deeds Brewing',
    'Pirate Life',
    'Rogue',
    'Heretic',
    'Thirsty',
    '4 Pines',
    'Schneider Weisse',
    'Blasta Brewing',
    'Rocky Ridge Brewing',
    'Alpine',
    'The Bruery',
    'Rocky Ridge',
    'Rodenbach',
    'Golden Road',
    'Stone Brewing',
    'Lindemans',
    'Heart of Darkness',
    'Lagunitas',
    'Founders',
    'Stone',
    'Behemoth',
    'New Belgium',
    'Trouble Brewing',
    'Mikkeller',
    'Deschutes',
    'Collective Arts Brewing',
    'Chouffe',
    'Coronado',
    'Green Flash',
    'Kaiju',
    'Little Creatures',
    'Great Divide',
    'Avery',
    'Sierra Nevada',
    'Deschutes',
    'Colonial',
    'Brewlander',
    'Nail',
    'Eagle Bay',
    'Hawkers',
    'Kona',
    'Holgate',
    'Garage Project',
    'Lost Coast',
]
