POPULAR_STYLES = [
    'Aged Sour Ale',
    'Weissbier',
    'Hoppy Saison',
    'DDH DIPA',
    'Fruited Sour',
    'Single Hop IPA',
    'Double Dry-hopped IPA',
    'Hazy DIPA',
    'Double Dry-hopped Double IPA',
    'Pilsner Beer',
    'Pineapple Sour IPA',
    'Oat Cream IPA',
    'Robust Porter',
    'Imperial Cream Sour',
    'Easy IPA',
    'Dry Hopped Kettle Sour',
    'Dark',
    'English Ale',
    'Dry Gin',
    'Session Hazy IPA',
    'Blackcurrant Lambic',
    'Salted Lime Gose',
    'Strong Pale Lager',
    'West Coast DIPA',
    'Fruit Gose',
    'Belgian Triple',
    'Whiskey',
    'Peach Lambic',
    'Red IPA',
    'Non-Alcoholic',
    'Belgian Double IPA',
    'Smoked',
    'Dry-hopped Sour Ale',
    'IIPA',
    'Barrel Aged Stout',
    'Seltzer',
    'Sour Fruited',
    'Belgian White Ale',
    'Alcoholic Seltzer',
    'Citrus Session IPA',
    'Craft Beer',
    'Single Estate Tequila',
    'Imperial Chocolate Stout',
    'DDH Hazy IPA',
    'Maibock',
    'Belgian Quadrupel',
    'Unfiltered Double IPA',
    'Witbier',
    'Oatmeal Stout',
    'Extra Pale Ale',
    'Pastry Stout',
    'Black IPA',
    'Milk Stout',
    'Barrel Aged Imperial Stout',
    'Ice Cream Sour',
    'Cocktail',
    'Red Rice Ale',
    'Wild Ale',
    'Wit Beer',
    'Golden Tripel',
    'Sour IPA',
    'Trappist',
    'DDH IPA',
    'Fruit Ale',
    'Imperial Pastry Stout',
    'Barley Wine',
    'Cream Ale',
    'Ginger Beer',
    'Flanders Red Ale',
    'Summer Ale',
    'Triple IPA',
    'Russian Imperial Stout',
    'Hazy Pale Ale',
    'Indian Pale Ale',
    'Tropical Pale Ale',
    'Hazy Double IPA',
    'White Ale',
    'DIPA',
    'Fruited Sour Ale',
    'Strong Ale',
    'Session Pale Ale',
    'Brown Ale',
    'Saison',
    'American IPA',
    'American Pale Ale',
    'Sour',
    'Lambic',
    'Pale Lager',
    'Dubbel',
    'West Coast IPA',
    'Session Ale',
    'Imperial Stout',
    'Dark Ale',
    'India Pale Ale',
    'NEIPA',
    'Double IPA',
    'Hazy IPA',
    'Quadrupel',
    'Amber Ale',
    'Wheat',
    'New England IPA',
    'Tripel',
    'Mead',
    'Porter',
    'Fruit Beer',
    'Ale',
    'Wheat Beer',
    'Pilsner',
    'Imperial IPA',
    'Wheat Ale',
    'Cider',
    'Hazy Ale',
    'Gose',
    'Session IPA',
    'Golden Ale',
    'Sour Ale',
    'Belgian Ale',
    'Stout',
    'Lager',
    'Pale Ale',
    'IPA',
]


POPULAR_BRANDS = [
    'Tooheys',
    'Kingfisher',
    'Coopers Brewery',
    'Westmalle Brewery',
    'LAOSHAN',
    'Beerfest',
    'Hawkes Brewery',
    'Zeffer Cider Co.',
    'Stone And Wood',
    'Redpoint Brewing',
    'Thirsty Beer Shop',
    'Redpoint Brewing Co.',
    'LINDEMANS',
    'VEDETT',
    'Radeberger',
    'Darling Brew',
    'Budweiser',
    'Hacker-Pschorr',
    'Woodstock Brewery',
    'Boatrocker Brewery',
    'Hop Nation Brewing Co',
    'Steinlager',
    'Fruli',
    'Mornington Peninsula Brewery',
    'Fraser\'s Folly',
    'To Ol',
    'Offshoot Beer Co.',
    'Dab Dortmunder',
    'GREVENSTEINER',
    'Benediktiner',
    'Dainton',
    'The Hills Cider',
    'Kronenbourg',
    'Jever',
    'Moondog',
    'High West Distillery',
    'Urbanaut',
    'Brouwerij Boon',
    'Franzikaner',
    'Westmalle Trappist',
    'Urbanaut Brewing Co',
    'Root Sellers Inc',
    'Firestone Walker',
    'Chimay',
    'Bodriggy',
    'Pilsner Urquell',
    'Trappistes Rochefort',
    'Älska Brewery',
    'Lotte Chilsung',
    'James Squire',
    'Wilde',
    'Cigar City',
    'bira91',
    'Burley Oak Brewing Company',
    'Modern Times',
    'SCHNEIDER WEISSE',
    'Boon',
    'Yoho Brewing Company',
    'Tsingtao',
    'Stockade Brew',
    'Tequila Corazón de Agave',
    'Amager Bryghus',
    'Mort Subite',
    'Sweetwater',
    'North Coast Brewing Company',
    'Spoetzl',
    'Blue Moon',
    'Wychwood Brewery',
    'Brasserie Dupont',
    'Redpoint Brewing Company',
    'Fremont',
    'Beerfarm',
    'Sailor\'s Grave Brewing',
    'Little Creatures Brewery',
    'Specific Gravity Beverage Company',
    'Pasteur Street',
    'Duncan\'s',
    'Fourpure',
    'Schfferhofer',
    'Buffalo Trace Distillery',
    'Kasteel',
    'Parrotdog',
    'Zeffer',
    'American Taproom x Spiffy Dapper',
    'Drakes',
    'Pasteur Street Brewing Co.',
    'Kapuziner',
    'Soul Barrel',
    'Bodriggy Brewing Co.',
    'Thatchers',
    'Off Day',
    'Fourpure Brewing Co.',
    'Chillhops Brewing',
    'Verhaeghe',
    'KAISERDOM',
    'Hobo Brewing',
    'Dupont Tourpes',
    'SweetWater Brewing Co.',
    'Hitachino Nest Beer',
    'Moon Dog',
    'Stone & Wood',
    'Omnipollo',
    'Rye & Pint',
    'Anderson Valley',
    'North Coast Brewing',
    'Hitachino Nest',
    'North Coast Brewing Co.',
    'Rogue Ales',
    'Gweilo',
    'To Øl',
    'Veltins',
    'Liberty Brewing',
    'Boon Oude Geuze',
    'Moon Dog Brewery',
    'Orval',
    'Pabst',
    'Brooklyn',
    'Brouwerij Verhaeghe',
    'Young Master Brewery',
    'Fourpure Brewing Co',
    'Stockade Brew Co',
    'Dupont',
    'Estrella',
    'Samuel Adams',
    'Gosnells Mead',
    'Coedo',
    'Gosnells of London',
    'No Brand',
    'Dogfish Head',
    'Brouwerij 3 Fonteinen',
    'Otherside Brewing',
    'LA TRAPPE',
    'Hoegaarden',
    'Epic Brewing Company',
    'TAIWAN BEER',
    'Two Tribes',
    'Rochefort Brewery',
    'Affligem',
    'Barossa Valley Brewing',
    'Brouwerij St. Bernardus',
    'Epic Brewing',
    'Devil\'s Peak',
    'Paulaner',
    'Archipelago',
    'Co-conspirators Brewing Co',
    'Sierra Nevada Brewing Co.',
    'Deep Creek',
    'Delirium',
    'Levante',
    'Gosnells',
    'Adroit Theory Brewing',
    'Gorilla',
    'Thatchers Cider',
    'Pabst Blue Ribbon',
    'Sweetwater Brewery',
    'La Trappe',
    '3 Fonteinen',
    'Leffe',
    'ParrotDog',
    'Founders Brewing',
    'Erdinger',
    'Van Honsebrouck',
    'Van Steenberge',
    'Chillhops Brewing Co.',
    'Ska',
    'Lion Brewery',
    'Otherside Brewing Co.',
    'Gage Roads',
    'The 1925 Brewing Company',
    'Maui',
    'Salt Beer Factory',
    'Founders Brewing Co.',
    'Pirate Life Brewing',
    'Atomic',
    'Westmalle',
    'Feral Brewing Co',
    'The 1925 Brewing Co.',
    'St Bernardus',
    'Heretic Brewing Co.',
    'Magic Rock Brewing',
    'Brewerkz',
    'Rochefort',
    'Huyghe',
    'Behemoth Brewing',
    'Bosteels',
    'Deep Creek Brewing Company',
    'Wychwood',
    'Young Master',
    'Pizza Port',
    'Mother Earth',
    'Vocation Brewery',
    'Founders Brewing Co',
    'Heretic Brewing Company',
    'Anderson Valley Brewing',
    'Thornbridge',
    'Brewlander & Co',
    'Mike Hess',
    'Stockade',
    'Stone Brewing Co.',
    'Vedett',
    'Off Day Beer Company',
    'Otherside Brewing Company',
    'Lion City Meadery',
    'St. Bernardus',
    'Wayward',
    'Anderson Valley Brewing Co.',
    'Brothers',
    'Duvel',
    'Playground Brewery',
    'BrewDog',
    'Epic',
    'Gorilla Brewing',
    'Blasta Brewing Co.',
    'Deeds Brewing',
    'Pirate Life',
    'Rogue',
    'Heretic',
    'Thirsty',
    '4 Pines',
    'Schneider Weisse',
    'Blasta Brewing',
    'Rocky Ridge Brewing Co.',
    'Alpine',
    'The Bruery',
    'Rocky Ridge',
    'Rodenbach',
    'Golden Road',
    'Stone Brewing',
    'Lindemans',
    'Heart of Darkness',
    'Lagunitas',
    'Founders',
    'Stone',
    'Behemoth Brewing Company',
    'New Belgium',
    'Trouble Brewing',
    'Mikkeller',
    'Deschutes Brewery',
    'Collective Arts Brewing',
    'Chouffe',
    'Coronado',
    'Green Flash',
    'Kaiju',
    'Little Creatures',
    'Great Divide',
    'Avery',
    'Sierra Nevada',
    'Deschutes',
    'Colonial',
    'Brewlander',
    'Nail',
    'Eagle Bay',
    'Hawkers',
    'Kona',
    'Holgate',
    'Garage Project',
    'Lost Coast',
]
