styles = [
    "Zero Alcohol Cider",
    "Wit Beer",
    "Wild Ale",
    "White Ale",
    "Wheat Beer",
    "Wheat Ale with Cherry",
    "Wheat Ale",
    "West Coast Pale Ale",
    "West Coast IPA",
    "West Coast DIPA",
    "Weissbier",
    "Watermelon Mint Sour",
    "Unfiltered IPA",
    "Unfiltered Double IPA",
    "Tropical Pale Ale",
    "Triple IPA",
    "Triple Hazy IPA",
    "Tripel",
    "Summer Ale",
    "Strong Ale",
    "Straight Rye Whiskey Blend",
    "Straight Rye Whiskey",
    "Straight Bourbon Whiskey Blend",
    "Straight Bourbon",
    "Stout",
    "Spontaneous 3 Year Sour Ale",
    "Spiced Porter",
    "Spanish Cava",
    "Sour NEIPA",
    "Sour IPA",
    "Sour Cherry Ale",
    "Sour Ale",
    "Single Malt Whisky",
    "Single Malt Whiskey",
    "Single Hop IPA",
    "Single Estate Tequila",
    "Session Pale Ale",
    "Session IPA",
    "Session Hazy IPA",
    "Session Ale",
    "Seltzer",
    "Scotch Style Ale",
    "Sauvignon Blanc",
    "Salted Lime Gose",
    "Saison",
    "Russian Imperial Stout",
    "Robust Porter",
    "Red Rice Ale",
    "Red India Pale Ale",
    "Raspberry Lambic",
    "Quadrupel",
    "Pumpkin Ale",
    "Porter",
    "Pinot Noir",
    "Pineapple Sour IPA",
    "Pilsner Beer",
    "Pilsner",
    "Peach Lambic",
    "Pastry Stout",
    "Pastry Sour",
    "Pale Lager",
    "Pale Ale (Session)",
    "Pale Ale",
    "Pacific Pale Ale",
    "Oud Bruin",
    "Oatmeal Stout",
    "Oat IPA",
    "Oaked Festbier",
    "Oak Aged Cider",
    "NZ Pale Ale w/ Passionfruit, Pineapple, Mango",
    "Non-alcoholic Wheat Beer",
    "Non-Alcoholic Pale Ale",
    "Non-alcoholic Dark Ale",
    "New Zealand DIPA",
    "New England IPA",
    "NEIPA",
    "Märzen Lager",
    "Mixed Culture Sour Ale",
    "Milk Stout",
    "Milkshake IPA",
    "Mead",
    "Maibock",
    "Low Calorie Hazy Pale Ale",
    "Lime Sour",
    "Lambic - Kriek",
    "Lambic - Gueuze",
    "Lambic - Framboise",
    "Lambic",
    "Lager with Salt & Lime",
    "Lager",
    "Kolsh",
    "Kentucky Straight Bourbon Whiskey",
    "Kentucky Straight Bourbon Whiskey",
    "Juicy Pale Ale",
    "Japanese Classic Ale",
    "IPA",
    "India Pale Lager",
    "India Pale Ale",
    "Indian Pale Ale",
    "Imperial Stout with Pineapple and Coconut",
    "Imperial Stout",
    "Imperial Saison",
    "Imperial Pilsner",
    "Imperial Pastry Stout",
    "Imperial Oatmeal Stout",
    "Imperial IPA",
    "Imperial Chocolate Stout",
    "Imperial Brown Ale",
    "Ice Cream Sour",
    "Hoppy Saison",
    "Hoppy Bretzel Ale",
    "Hop Oil DIPA",
    "Honey & Cherry Sour",
    "Hibiscus Watermelon Sour",
    "Hazy Triple IPA",
    "Hazy Pastry DIPA",
    "Hazy Pale Ale",
    "Hazy IPA",
    "Hazy Dry-hopped Double IPA",
    "Hazy Double IPA",
    "Hazy DIPA",
    "Hazy Ale",
    "Hard Seltzer",
    "Hard Seltzer",
    "Gose",
    "Golden Tripel",
    "Golden Ale",
    "Gluten-Free Pale Ale",
    "Fruit Gose",
    "Fruited Wheat Ale",
    "Fruited Sour Ale",
    "Fruited Sour",
    "Fruit Beer",
    "Fruit Ale",
    "Flanders Red Ale",
    "Festive IPA",
    "Extra Pale Ale",
    "Espresso Martini Stout",
    "English Ale",
    "East Coast IPA",
    "Dubbel",
    "Dry Stout",
    "Dry Lager",
    "Dry Hopped Kettle Sour",
    "Dry Hopped IPA",
    "Dry Gin",
    "Dry-hopped Sour Ale",
    "Dry-hopped Pilsner",
    "Double Hazy IPA",
    "Double IPA",
    "Double Hazy IPA",
    "Double Dry-hopped IPA",
    "Double Dry-hopped Double IPA",
    "Double Chocolate Stout",
    "Double Chocolate Coffee Oatmeal Stout",
    "DIPA",
    "DDH Oat Cream Imperial IPA",
    "DDH Hazy IPA",
    "DDH DIPA",
    "Dark Ale",
    "Danish Wild Ale",
    "Cucumber and Mint Sour Ale",
    "Cream Ale",
    "Craft Beer",
    "Cocktail",
    "Citrus Session IPA",
    "Citrus IPA",
    "Cider",
    "Chocolate Raspberry Stout",
    "Chilli, Mango, Lime IPA",
    "Cherry Lambic",
    "Chardonnay Barrel Aged Brett Saison",
    "Chardonnay",
    "Cascadian Ale with Rye",
    "Cabernet Sauvignon / Merlot Hawke's Bay",
    "Cabernet Sauvignon",
    "Brown Ale",
    "Brett Summer Ale",
    "Bourbon Finished in Port Wine Barrels",
    "Blue Agave Triple Distilled Tequila",
    "Black IPA",
    "Blackcurrant Lambic",
    "Belgian Ale",
    "Belgian Wit Ale",
    "Belgian White Ale",
    "Belgian Triple",
    "Belgian Tripel",
    "Belgian Strong Dark Ale",
    "Belgian IPA",
    "Belgian Double IPA",
    "Belgian Ale",
    "Belgian-Style Pale Ale",
    "Bavarian Style Wheat",
    "Barrel Aged Sour Ale",
    "Barrel Aged Imperial Stout with Coffee",
    "Barrel Aged Imperial Stout",
    "Barrel Aged Belgian Tripel",
    "Barrel-Aged Saison",
    "Barrel-aged Russian Imperial Stout",
    "Barrel-aged Porter",
    "Barrel-aged Imperial Stout",
    "Barleywine Style Ale",
    "Barley Wine",
    "Apple Lambic",
    "American Strong Ale",
    "American Pale Ale",
    "American IPA",
    "American Hefeweizen",
    "American Gin",
    "Amber Ale",
    "Ale",
    "Alcoholic Seltzer",
    "Alcohol Free IPA",
    "Alcohol-free Lager",
    "Albariño Wine",
    "Aged Sour Ale",
]
